---
- hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    zone: dev.iisl.com
    zone_file: "/var/named/dynamic/db.dev.iisl.com"
#    zone_file: db.dev.iisl.com
    ipaddress: 172.18.10.232
    hostname: dummy2
    dns_server: dvnv-rhsat01.dev.iisl.com

  tasks:
  - name: Add record
    nsupdate:
      key_name: "key"
      key_secret: ""
      key_algorithm: "hmac-sha256"
      server: "{{ dns_server }}"
      zone: "{{ zone }}"
      record: "{{ hostname }}"
      value: "{{ ipaddress }}"
      state: absent
