---
- name: Update forward and reverse zone files
  hosts: localhost
  connection: smart
  gather_facts: no

  vars:
    servers:
    - zone: dev.iisl.com
      zone_file: db.dev.iisl.com
      ipaddress: 172.18.10.123
      cidr: 172.18.0.0/16
      hostname: dummy1
      ptr_zone_file: db.10.18.172.in-addr.arpa
    - zone: dev.iisl.com
      zone_file: db.dev.iisl.com
      ipaddress: 172.18.10.213
      hostname: dummy2
      ptr_zone: 18.172.in-addr.arpa
      ptr_zone_file: db.10.18.172.in-addr.arpa

  tasks:
  - name: Call update_zone
    include_role:
      name: update_zone
    vars:
      r_zone: "{{ server.zone }}"
      r_zone_file: "{{ server.zone_file }}"
      r_ipaddress: "{{ server.ipaddress }}"
      r_hostname: "{{ server.hostname }}"
      r_ptr_zone: "{{ server.ptr_zone | default(none) }}"
      r_ptr_zone_file: "{{ server.ptr_zone_file }}"
      r_cidr: "{{ server.cidr | default(none) }}"
    loop: "{{ servers }}"
    loop_control:
      loop_var: server
      label: "{{ server.hostname }}"
