---
- name: Confirm ipaddress is valid
  assert:
    that:
    - ipaddress | ipv4
    - ipaddress | regex_replace('[0-9]','') == "..."
    fail_msg: " IP address {{ ipaddress }} is invalid."

#- name: Confirm revers network address is valid
#  assert:
#    that:
#    - 
  
- name: Update forward zone file
  include_tasks:
      file: update_forward_zone.yml
  when:
  - zone_file is defined
  - zone is defined
  - hostname is defined
  - ipaddress is defined

- name: Update reverse zone file
  include_tasks:
      file: update_reverse_zone.yml
  when:
  - zone is defined
  - ptr_zone_file is defined
  - ptr_zone is defined
  - hostname is defined
  - ipaddress is defined
